/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az3cr4partie2;

import javax.swing.ImageIcon;

/**
 *
 * @author Le Padre
 */
public class DJfmMeteo extends javax.swing.JFrame {

    /**
     * Creates new form DJfmMeteo
     */
    public DJfmMeteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRbtSoleil = new javax.swing.JRadioButton();
        jRbtNuage = new javax.swing.JRadioButton();
        jRbtNeige = new javax.swing.JRadioButton();
        jLblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Météo");
        setBounds(new java.awt.Rectangle(300, 300, 600, 200));

        buttonGroup1.add(jRbtSoleil);
        jRbtSoleil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRbtSoleil.setSelected(true);
        jRbtSoleil.setText("Soleil");
        jRbtSoleil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtSoleilActionPerformed(evt);
            }
        });
        jPanel1.add(jRbtSoleil);

        buttonGroup1.add(jRbtNuage);
        jRbtNuage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRbtNuage.setText("Nuage");
        jRbtNuage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtNuageActionPerformed(evt);
            }
        });
        jPanel1.add(jRbtNuage);

        buttonGroup1.add(jRbtNeige);
        jRbtNeige.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRbtNeige.setText("Neige");
        jRbtNeige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtNeigeActionPerformed(evt);
            }
        });
        jPanel1.add(jRbtNeige);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jLblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az3cr4partie2/Images/meteosoleil.png"))); // NOI18N
        getContentPane().add(jLblImage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRbtNeigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtNeigeActionPerformed
       jLblImage.setIcon(new ImageIcon(getClass().getResource("Images/meteoneige.png")));

    }//GEN-LAST:event_jRbtNeigeActionPerformed

    private void jRbtSoleilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtSoleilActionPerformed
       jLblImage.setIcon(new ImageIcon(getClass().getResource("Images/meteosoleil.png")));
    }//GEN-LAST:event_jRbtSoleilActionPerformed

    private void jRbtNuageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtNuageActionPerformed
       jLblImage.setIcon(new ImageIcon(getClass().getResource("Images/meteonuage.png")));
    }//GEN-LAST:event_jRbtNuageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DJfmMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DJfmMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DJfmMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DJfmMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DJfmMeteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLblImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRbtNeige;
    private javax.swing.JRadioButton jRbtNuage;
    private javax.swing.JRadioButton jRbtSoleil;
    // End of variables declaration//GEN-END:variables
}
