/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testmvc;

import java.util.Observer;
import javafx.beans.Observable;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author TALLER
 */


public class VueArticle extends JFrame implements Observer{
//public static ModeleVueArticle mva=new ModeleVueArticle();
    /**
     * Creates new form Windows
     */
    public VueArticle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to  the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BrTop = new javax.swing.JPanel();
        Premier = new javax.swing.JButton();
        Suivant = new javax.swing.JButton();
        PrÈcÈdent = new javax.swing.JButton();
        Dernier = new javax.swing.JButton();
        BrCenter = new javax.swing.JPanel();
        pCodeA = new javax.swing.JPanel();
        iz = new javax.swing.JPanel();
        centre = new javax.swing.JPanel();
        codeArticle = new javax.swing.JLabel();
        codeA = new javax.swing.JTextField();
        Desig = new javax.swing.JLabel();
        desA = new javax.swing.JTextField();
        codeCategorie = new javax.swing.JLabel();
        codeC = new javax.swing.JTextField();
        prixUnitaire = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        der = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        BrSouth = new javax.swing.JPanel();
        Nouveau = new javax.swing.JButton();
        Ajouter = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Article");

        jPanel1.setLayout(new java.awt.BorderLayout());

        BrTop.setLayout(new java.awt.GridLayout(0, 4));

        Premier.setText("Premier");
        Premier.setPreferredSize(new java.awt.Dimension(130, 45));
        BrTop.add(Premier);

        Suivant.setText("Suivant");
        Suivant.setPreferredSize(new java.awt.Dimension(130, 45));
        BrTop.add(Suivant);

        PrÈcÈdent.setText("PrÈcÈdent");
        PrÈcÈdent.setPreferredSize(new java.awt.Dimension(130, 45));
        BrTop.add(PrÈcÈdent);

        Dernier.setText("Dernier");
        Dernier.setPreferredSize(new java.awt.Dimension(130, 45));
        BrTop.add(Dernier);

        jPanel1.add(BrTop, java.awt.BorderLayout.NORTH);

        BrCenter.setPreferredSize(new java.awt.Dimension(588, 300));
        BrCenter.setLayout(new java.awt.BorderLayout());

        pCodeA.setPreferredSize(new java.awt.Dimension(650, 300));
        pCodeA.setLayout(new java.awt.BorderLayout());

        iz.setPreferredSize(new java.awt.Dimension(90, 0));

        javax.swing.GroupLayout izLayout = new javax.swing.GroupLayout(iz);
        iz.setLayout(izLayout);
        izLayout.setHorizontalGroup(
            izLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        izLayout.setVerticalGroup(
            izLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pCodeA.add(iz, java.awt.BorderLayout.WEST);

        centre.setToolTipText("");
        centre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centre.setPreferredSize(new java.awt.Dimension(650, 300));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING);
        flowLayout1.setAlignOnBaseline(true);
        centre.setLayout(flowLayout1);

        codeArticle.setText("Code Article");
        codeArticle.setMaximumSize(new java.awt.Dimension(70, 20));
        codeArticle.setPreferredSize(new java.awt.Dimension(140, 30));
        centre.add(codeArticle);

        codeA.setName(""); // NOI18N
        codeA.setPreferredSize(new java.awt.Dimension(160, 30));
        centre.add(codeA);

        Desig.setText("Designation Article");
        Desig.setMaximumSize(new java.awt.Dimension(70, 20));
        Desig.setPreferredSize(new java.awt.Dimension(140, 30));
        centre.add(Desig);

        desA.setPreferredSize(new java.awt.Dimension(220, 30));
        centre.add(desA);

        codeCategorie.setText("Code Categorie");
        codeCategorie.setMaximumSize(new java.awt.Dimension(70, 20));
        codeCategorie.setPreferredSize(new java.awt.Dimension(140, 30));
        centre.add(codeCategorie);

        codeC.setMaximumSize(new java.awt.Dimension(0, 0));
        codeC.setPreferredSize(new java.awt.Dimension(160, 30));
        centre.add(codeC);

        prixUnitaire.setText("Prix Unitaire");
        prixUnitaire.setMaximumSize(new java.awt.Dimension(70, 20));
        prixUnitaire.setPreferredSize(new java.awt.Dimension(140, 30));
        centre.add(prixUnitaire);

        prix.setPreferredSize(new java.awt.Dimension(120, 30));
        centre.add(prix);

        pCodeA.add(centre, java.awt.BorderLayout.CENTER);

        der.setPreferredSize(new java.awt.Dimension(130, 0));

        javax.swing.GroupLayout derLayout = new javax.swing.GroupLayout(der);
        der.setLayout(derLayout);
        derLayout.setHorizontalGroup(
            derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        derLayout.setVerticalGroup(
            derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pCodeA.add(der, java.awt.BorderLayout.EAST);

        top.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pCodeA.add(top, java.awt.BorderLayout.NORTH);

        BrCenter.add(pCodeA, java.awt.BorderLayout.CENTER);

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Cette application vous permet de parcourir et modifier les enregistrements de la table Article.");
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label.setPreferredSize(new java.awt.Dimension(588, 30));
        BrCenter.add(label, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(BrCenter, java.awt.BorderLayout.CENTER);

        BrSouth.setLayout(new java.awt.GridLayout(0, 5));

        Nouveau.setText("Nouveau");
        Nouveau.setPreferredSize(new java.awt.Dimension(130, 45));
        BrSouth.add(Nouveau);

        Ajouter.setText("Ajouter");
        Ajouter.setPreferredSize(new java.awt.Dimension(130, 45));
        BrSouth.add(Ajouter);

        Annuler.setText("Annuler");
        Annuler.setPreferredSize(new java.awt.Dimension(130, 45));
        BrSouth.add(Annuler);

        Modifier.setText("Modifier");
        Modifier.setPreferredSize(new java.awt.Dimension(130, 45));
        BrSouth.add(Modifier);

        Supprimer.setText("Supprimer");
        Supprimer.setPreferredSize(new java.awt.Dimension(130, 45));
        BrSouth.add(Supprimer);

        jPanel1.add(BrSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }
    
    // Getters de les boutons
    
    public JButton getAjouter() {
        return Ajouter;
    }

    public JButton getSuivant() {
        return Suivant;
    }

    public JButton getAnnuler() {
        return Annuler;
    }

    public JButton getDernier() {
        return Dernier;
    }

    public JButton getModifier() {
        return Modifier;
    }

    public JButton getNouveau() {
        return Nouveau;
    }

    public JButton getPremier() {
        return Premier; 
    }

    public JButton getPrecedent() {
        return PrÈcÈdent;
    }

    public JButton getSupprimer() {
        return Supprimer;
    }

    public JTextField getCodeA() {
        return desA;
    }

    public JTextField getCodeC() {
        return codeA;
    }

    public JTextField getDesA() {
        return codeC;
    }

    public JTextField getPrix() {
        return prix;
    }

    public JLabel getLabel() {
        return label;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel BrCenter;
    private javax.swing.JPanel BrSouth;
    private javax.swing.JPanel BrTop;
    private javax.swing.JButton Dernier;
    private javax.swing.JLabel Desig;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Nouveau;
    private javax.swing.JButton Premier;
    private javax.swing.JButton PrÈcÈdent;
    private javax.swing.JButton Suivant;
    private javax.swing.JButton Supprimer;
    private javax.swing.JPanel centre;
    private javax.swing.JTextField codeA;
    private javax.swing.JLabel codeArticle;
    private javax.swing.JTextField codeC;
    private javax.swing.JLabel codeCategorie;
    private javax.swing.JPanel der;
    private javax.swing.JTextField desA;
    private javax.swing.JPanel iz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel pCodeA;
    private javax.swing.JTextField prix;
    private javax.swing.JLabel prixUnitaire;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables

    
    //La methode update recupere le resultat du model quand il est notifié par 
    // le model
    @Override
    public void update(java.util.Observable o, Object obj) {
         String codeArt     = ((Article)obj).getCodeArticle();
         String desArt      = ((Article)obj).getDesignationArticle();
         String categorie   = ((Article)obj).getCodeCategorie();
         double prixObj     = ((Article)obj).getPrixUnitaire();
         
         codeA.setText(codeArt.toString());
         desA.setText(desArt.toString());
         codeC.setText(categorie.toString());
         prix.setText(String.valueOf(prixObj));
         //label.setText("OK");
        
    }

    
}
