/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az3tp1;

/**
 *
 * @author mk
 */
public class AdressesCourriel extends javax.swing.JFrame {

    /**
     * Creates new form AdressesCourriel
     */
    public AdressesCourriel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NordPanel = new javax.swing.JPanel();
        Prenom = new javax.swing.JLabel();
        InputPrenom = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        InputNom = new javax.swing.JTextField();
        CenterPanel = new javax.swing.JPanel();
        Nord = new javax.swing.JPanel();
        JLCourriel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Center = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        East = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SouthPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        SudPanel = new javax.swing.JPanel();
        OK = new javax.swing.JButton();
        OK1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adresse Courriel");
        setPreferredSize(new java.awt.Dimension(700, 400));

        NordPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        NordPanel.setToolTipText("");
        NordPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        Prenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Prenom.setText("Prénom");
        Prenom.setMaximumSize(new java.awt.Dimension(120, 16));
        Prenom.setMinimumSize(new java.awt.Dimension(50, 16));
        Prenom.setPreferredSize(new java.awt.Dimension(50, 16));
        Prenom.setSize(new java.awt.Dimension(50, 16));
        NordPanel.add(Prenom);

        InputPrenom.setToolTipText("");
        InputPrenom.setPreferredSize(new java.awt.Dimension(150, 25));
        InputPrenom.setSize(new java.awt.Dimension(100, 22));
        NordPanel.add(InputPrenom);

        Nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nom.setText("Prénom");
        Nom.setMaximumSize(new java.awt.Dimension(120, 16));
        Nom.setMinimumSize(new java.awt.Dimension(50, 16));
        Nom.setPreferredSize(null);
        Nom.setRequestFocusEnabled(false);
        NordPanel.add(Nom);

        InputNom.setToolTipText("");
        InputNom.setPreferredSize(new java.awt.Dimension(150, 25));
        InputNom.setSize(new java.awt.Dimension(100, 22));
        NordPanel.add(InputNom);

        getContentPane().add(NordPanel, java.awt.BorderLayout.NORTH);

        CenterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        CenterPanel.setLayout(new java.awt.BorderLayout());

        JLCourriel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JLCourriel.setText("Adresse Courriel :");
        JLCourriel.setToolTipText("");
        JLCourriel.setMaximumSize(new java.awt.Dimension(120, 16));
        JLCourriel.setMinimumSize(new java.awt.Dimension(50, 16));
        JLCourriel.setRequestFocusEnabled(false);
        Nord.add(JLCourriel);

        jTextField1.setText("pre");
        jTextField1.setPreferredSize(new java.awt.Dimension(450, 22));
        Nord.add(jTextField1);

        CenterPanel.add(Nord, java.awt.BorderLayout.NORTH);

        Center.setLayout(new java.awt.BorderLayout(0, 5));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("adresse1\nadresse2\nadresse3");
        jScrollPane1.setViewportView(jTextArea1);

        Center.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        East.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        East.setPreferredSize(new java.awt.Dimension(120, 120));
        East.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jButton1.setText("Ajouter");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 50));
        East.add(jButton1);

        jButton2.setText("Editer");
        East.add(jButton2);

        jButton3.setText("Supprimer");
        East.add(jButton3);

        jButton4.setText("ParDéfaut");
        East.add(jButton4);

        Center.add(East, java.awt.BorderLayout.EAST);

        SouthPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SouthPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("HTML");
        SouthPanel.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Texte");
        SouthPanel.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Autre");
        SouthPanel.add(jRadioButton3);

        Center.add(SouthPanel, java.awt.BorderLayout.SOUTH);
        SouthPanel.getAccessibleContext().setAccessibleName("");

        CenterPanel.add(Center, java.awt.BorderLayout.PAGE_END);
        Center.getAccessibleContext().setAccessibleName("");

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        SudPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        SudPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        OK.setText("OK");
        SudPanel.add(OK);

        OK1.setText("Annuler");
        SudPanel.add(OK1);

        getContentPane().add(SudPanel, java.awt.BorderLayout.SOUTH);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdressesCourriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdressesCourriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdressesCourriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdressesCourriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdressesCourriel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel East;
    private javax.swing.JTextField InputNom;
    private javax.swing.JTextField InputPrenom;
    private javax.swing.JLabel JLCourriel;
    private javax.swing.JLabel Nom;
    private javax.swing.JPanel Nord;
    private javax.swing.JPanel NordPanel;
    private javax.swing.JButton OK;
    private javax.swing.JButton OK1;
    private javax.swing.JLabel Prenom;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel SudPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
