/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az3cr5menuetdialogue;

import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author win7
 */
public class DjfmDialogue1 extends javax.swing.JFrame {

    /**
     * Creates new form Cr7Dialogue1
     */
    public DjfmDialogue1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jSaisirNom = new javax.swing.JMenuItem();
        jChoisirNom = new javax.swing.JMenuItem();
        jOuvrirNom = new javax.swing.JMenuItem();
        jQuitter = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCouleurFond = new javax.swing.JMenuItem();
        jCouleurText = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boites de Dialogue");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Les Boites de Dialogues");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu3.setMnemonic('F');
        jMenu3.setText("Fichier");

        jSaisirNom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSaisirNom.setMnemonic('S');
        jSaisirNom.setText("Saisir Nom ");
        jSaisirNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaisirNomActionPerformed(evt);
            }
        });
        jMenu3.add(jSaisirNom);

        jChoisirNom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jChoisirNom.setMnemonic('n');
        jChoisirNom.setText("Choisir Nom");
        jChoisirNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChoisirNomActionPerformed(evt);
            }
        });
        jMenu3.add(jChoisirNom);

        jOuvrirNom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jOuvrirNom.setMnemonic('O');
        jOuvrirNom.setText("Ouvrir Image");
        jOuvrirNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOuvrirNomActionPerformed(evt);
            }
        });
        jMenu3.add(jOuvrirNom);

        jQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jQuitter.setMnemonic('Q');
        jQuitter.setText("Quitter");
        jQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuitterActionPerformed(evt);
            }
        });
        jMenu3.add(jQuitter);

        jMenuBar2.add(jMenu3);

        jMenu4.setMnemonic('E');
        jMenu4.setText("Editer");

        jCouleurFond.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jCouleurFond.setMnemonic('F');
        jCouleurFond.setText("Couleur Fond");
        jCouleurFond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCouleurFondActionPerformed(evt);
            }
        });
        jMenu4.add(jCouleurFond);

        jCouleurText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jCouleurText.setMnemonic('T');
        jCouleurText.setText("Couleur Text");
        jCouleurText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCouleurTextActionPerformed(evt);
            }
        });
        jMenu4.add(jCouleurText);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //boite confirmation
    private void jQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuitterActionPerformed
        
         if (JOptionPane.showConfirmDialog(this, "Désirez-vous quitter l'application ?")
              == JOptionPane.YES_OPTION) System.exit(0); 
    }//GEN-LAST:event_jQuitterActionPerformed

    //sélecteur de fichiers
    private void jOuvrirNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOuvrirNomActionPerformed
      
                JFileChooser sélecteur = new JFileChooser("C:\\Users\\Le Padre\\Pictures");
                if (sélecteur.showDialog(this, "Sélectionner votre image")==JFileChooser.APPROVE_OPTION){
                    File fichier = sélecteur.getSelectedFile();
                    jLabel2.setIcon(new ImageIcon(fichier.getPath()));
                    this.setExtendedState(JFrame.MAXIMIZED_BOTH );
                }
                
    }//GEN-LAST:event_jOuvrirNomActionPerformed

    //saisie de nom
    private void jSaisirNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaisirNomActionPerformed
       
        String nomImage = JOptionPane.showInputDialog("Nom du fichier de l'image :");
        jLabel2.setText(nomImage);
    }//GEN-LAST:event_jSaisirNomActionPerformed

    //sélecteur de couleur
    private void jCouleurFondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCouleurFondActionPerformed
        
            Color couleur = JColorChooser.showDialog( null,"Couleur de fond", this.getBackground());
            if (couleur!=null) jPanel1.setBackground(couleur);
    }//GEN-LAST:event_jCouleurFondActionPerformed

    //sélecteur de couleur
    private void jCouleurTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCouleurTextActionPerformed
        
        Color couleur = JColorChooser.showDialog(this, "Couleur de Texte", this.getForeground());
            if (couleur!=null) jLabel1.setForeground(couleur);jLabel2.setForeground(couleur);
    }//GEN-LAST:event_jCouleurTextActionPerformed
    
    //sélecteur d'option
    private void jChoisirNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChoisirNomActionPerformed
        
        String[] choix = {"panorama_1", "panorama_2", "panorama_3"};
        String reponse = (String)JOptionPane.showInputDialog(null,
                                                                 "Choisir un nom d'image", 
                                                                 "Nom Image",  
                                                                 JOptionPane.QUESTION_MESSAGE, 
                                                                 null,
                                                                 choix, 
                                                                 null);
        jLabel2.setText(reponse);
    }//GEN-LAST:event_jChoisirNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DjfmDialogue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DjfmDialogue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DjfmDialogue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DjfmDialogue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DjfmDialogue1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jChoisirNom;
    private javax.swing.JMenuItem jCouleurFond;
    private javax.swing.JMenuItem jCouleurText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jOuvrirNom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jQuitter;
    private javax.swing.JMenuItem jSaisirNom;
    // End of variables declaration//GEN-END:variables
}
