/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mk
 */
public class VueArticle extends javax.swing.JFrame implements Observer{

    
    
    /**
     * Creates new form VueArticle
     */
    public VueArticle() {
        initComponents();
    }

    //Variable position
    int dernierPosition = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMain = new javax.swing.JPanel();
        jPNord = new javax.swing.JPanel();
        jBtnPremier = new javax.swing.JButton();
        jBtnSuivant = new javax.swing.JButton();
        jBtnPrecedent = new javax.swing.JButton();
        jBtnDernier = new javax.swing.JButton();
        jPCentre = new javax.swing.JPanel();
        jPNORD = new javax.swing.JPanel();
        jLCodeArticle = new javax.swing.JLabel();
        jTxtCodeArticle = new javax.swing.JTextField();
        jLDesignation = new javax.swing.JLabel();
        jTxtDesignation = new javax.swing.JTextField();
        jLCodeCategorie = new javax.swing.JLabel();
        jTxtCodeCategorie = new javax.swing.JTextField();
        jLPrixUnit = new javax.swing.JLabel();
        jTxtPrixUnit = new javax.swing.JTextField();
        jPSUD = new javax.swing.JPanel();
        jLMessage = new javax.swing.JLabel();
        jPSouth = new javax.swing.JPanel();
        jBtnNouveau = new javax.swing.JButton();
        jBtnAjout = new javax.swing.JButton();
        jBtnAnnuler = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jBtnSupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table Article");
        setBounds(new java.awt.Rectangle(0, 23, 700, 700));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPMain.setPreferredSize(new java.awt.Dimension(700, 650));
        jPMain.setLayout(new java.awt.BorderLayout());

        jPNord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPNord.setPreferredSize(new java.awt.Dimension(630, 45));
        jPNord.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jBtnPremier.setText("Premier");
        jBtnPremier.setPreferredSize(new java.awt.Dimension(164, 43));
        jPNord.add(jBtnPremier);

        jBtnSuivant.setText("Suivant");
        jBtnSuivant.setPreferredSize(new java.awt.Dimension(164, 43));
        jPNord.add(jBtnSuivant);

        jBtnPrecedent.setText("Precedent");
        jBtnPrecedent.setPreferredSize(new java.awt.Dimension(164, 43));
        jPNord.add(jBtnPrecedent);

        jBtnDernier.setText("Dernier");
        jBtnDernier.setPreferredSize(new java.awt.Dimension(164, 43));
        jPNord.add(jBtnDernier);

        jPMain.add(jPNord, java.awt.BorderLayout.NORTH);

        jPCentre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPCentre.setPreferredSize(new java.awt.Dimension(630, 473));
        jPCentre.setLayout(new java.awt.BorderLayout());

        jPNORD.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 20, 150, 120));
        jPNORD.setPreferredSize(new java.awt.Dimension(656, 400));
        jPNORD.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLCodeArticle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCodeArticle.setText("Code Article");
        jLCodeArticle.setMinimumSize(new java.awt.Dimension(5, 16));
        jLCodeArticle.setPreferredSize(new java.awt.Dimension(20, 16));
        jPNORD.add(jLCodeArticle);

        jTxtCodeArticle.setText("jTextField1");
        jTxtCodeArticle.setSize(new java.awt.Dimension(50, 29));
        jTxtCodeArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodeArticleActionPerformed(evt);
            }
        });
        jPNORD.add(jTxtCodeArticle);

        jLDesignation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLDesignation.setText("Designation Article");
        jLDesignation.setMaximumSize(new java.awt.Dimension(200, 16));
        jLDesignation.setMinimumSize(new java.awt.Dimension(5, 16));
        jLDesignation.setPreferredSize(new java.awt.Dimension(20, 16));
        jPNORD.add(jLDesignation);

        jTxtDesignation.setText("Produt");
        jTxtDesignation.setToolTipText("");
        jTxtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDesignationActionPerformed(evt);
            }
        });
        jPNORD.add(jTxtDesignation);

        jLCodeCategorie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLCodeCategorie.setText("Code Catégorie");
        jLCodeCategorie.setMinimumSize(new java.awt.Dimension(5, 16));
        jLCodeCategorie.setPreferredSize(new java.awt.Dimension(20, 16));
        jPNORD.add(jLCodeCategorie);

        jTxtCodeCategorie.setText("0");
        jTxtCodeCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodeCategorieActionPerformed(evt);
            }
        });
        jPNORD.add(jTxtCodeCategorie);

        jLPrixUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLPrixUnit.setText("Prix Unitaire");
        jLPrixUnit.setMinimumSize(new java.awt.Dimension(5, 16));
        jLPrixUnit.setPreferredSize(new java.awt.Dimension(20, 16));
        jPNORD.add(jLPrixUnit);

        jTxtPrixUnit.setText("0");
        jTxtPrixUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrixUnitActionPerformed(evt);
            }
        });
        jPNORD.add(jTxtPrixUnit);

        jPCentre.add(jPNORD, java.awt.BorderLayout.CENTER);

        jPSUD.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPSUD.setPreferredSize(new java.awt.Dimension(656, 50));
        jPSUD.setLayout(new java.awt.BorderLayout());

        jLMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMessage.setText("Cette application vous permet de parcourir et de modifier les enregistrement de la table article");
        jPSUD.add(jLMessage, java.awt.BorderLayout.CENTER);

        jPCentre.add(jPSUD, java.awt.BorderLayout.SOUTH);

        jPMain.add(jPCentre, java.awt.BorderLayout.CENTER);

        jPSouth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPSouth.setPreferredSize(new java.awt.Dimension(630, 65));
        jPSouth.setLayout(new java.awt.GridBagLayout());

        jBtnNouveau.setText("Nouveau");
        jBtnNouveau.setPreferredSize(new java.awt.Dimension(131, 60));
        jBtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNouveauActionPerformed(evt);
            }
        });
        jPSouth.add(jBtnNouveau, new java.awt.GridBagConstraints());

        jBtnAjout.setText("Ajouter");
        jBtnAjout.setEnabled(false);
        jBtnAjout.setPreferredSize(new java.awt.Dimension(131, 60));
        jBtnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjoutActionPerformed(evt);
            }
        });
        jPSouth.add(jBtnAjout, new java.awt.GridBagConstraints());

        jBtnAnnuler.setText("Annuler");
        jBtnAnnuler.setEnabled(false);
        jBtnAnnuler.setPreferredSize(new java.awt.Dimension(131, 60));
        jBtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnulerActionPerformed(evt);
            }
        });
        jPSouth.add(jBtnAnnuler, new java.awt.GridBagConstraints());

        jBtnModifier.setText("Modfier");
        jBtnModifier.setPreferredSize(new java.awt.Dimension(131, 60));
        jPSouth.add(jBtnModifier, new java.awt.GridBagConstraints());

        jBtnSupprimer.setText("Supprimer");
        jBtnSupprimer.setPreferredSize(new java.awt.Dimension(131, 60));
        jPSouth.add(jBtnSupprimer, new java.awt.GridBagConstraints());

        jPMain.add(jPSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodeArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodeArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodeArticleActionPerformed

    private void jTxtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDesignationActionPerformed

    private void jTxtCodeCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodeCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodeCategorieActionPerformed

    private void jTxtPrixUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrixUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrixUnitActionPerformed

    private void jBtnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNouveauActionPerformed
        jTxtCodeArticle.setText("");
        jTxtCodeCategorie.setText("");
        jTxtDesignation.setText("");
        jTxtPrixUnit.setText("");

        //Sauvegarde du dernier position
        dernierPosition++;
        jLMessage.setText("Vous essayer d'ajouter un nouveau article " + dernierPosition);

        //Activation des boutons
        jBtnAjout.setEnabled(true);
        jBtnAnnuler.setEnabled(true);

        //esactive des boutons
        jBtnNouveau.setEnabled(false);
        jBtnSupprimer.setEnabled(false);
        jBtnPremier.setEnabled(false);
        jBtnSuivant.setEnabled(false);
        jBtnPrecedent.setEnabled(false);
        jBtnDernier.setEnabled(false);
        jBtnModifier.setEnabled(false);
    }//GEN-LAST:event_jBtnNouveauActionPerformed

    private void jBtnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjoutActionPerformed
        try {
            //Activation des boutons
            jBtnNouveau.setEnabled(true);
            jBtnSupprimer.setEnabled(true);
            jBtnPremier.setEnabled(true);
            jBtnSuivant.setEnabled(true);
            jBtnPrecedent.setEnabled(true);
            jBtnDernier.setEnabled(true);
            jBtnModifier.setEnabled(true);
            
            jLMessage.setText("Cette application vous permet de parcourir et de modifier les enregistrement de la table article");

            //desactive des boutons
            jBtnAjout.setEnabled(false);
            jBtnAnnuler.setEnabled(false);
            
            JOptionPane.showMessageDialog(this,"Article ajoute avec succe, et retour a la derniere position ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Une erreur s'est produite ");
        }
    }//GEN-LAST:event_jBtnAjoutActionPerformed

    private void jBtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnulerActionPerformed
        try {
            //Activation des boutons
            jBtnNouveau.setEnabled(true);
            jBtnSupprimer.setEnabled(true);
            jBtnPremier.setEnabled(true);
            jBtnSuivant.setEnabled(true);
            jBtnPrecedent.setEnabled(true);
            jBtnDernier.setEnabled(true);
            jBtnModifier.setEnabled(true);
            
            jLMessage.setText("Cette application vous permet de parcourir et de modifier les enregistrement de la table article");

            //desactive des boutons
            jBtnAjout.setEnabled(false);
            jBtnAnnuler.setEnabled(false);
            
            JOptionPane.showMessageDialog(this,"Annulé, et retour a la derniere position ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Une erreur s'est produite ");
        }
    }//GEN-LAST:event_jBtnAnnulerActionPerformed

    public int getDernierPosition() {
        return dernierPosition;
    }

    public void setDernierPosition(int dernierPosition) {
        this.dernierPosition = dernierPosition;
    }

    public JButton getjBtnAjout() {
        return jBtnAjout;
    }


    public JButton getjBtnAnnuler() {
        return jBtnAnnuler;
    }



    public JButton getjBtnDernier() {
        return jBtnDernier;
    }



    public JButton getjBtnModifier() {
        return jBtnModifier;
    }



    public JButton getjBtnNouveau() {
        return jBtnNouveau;
    }



    public JButton getjBtnPrecedent() {
        return jBtnPrecedent;
    }



    public JButton getjBtnPremier() {
        return jBtnPremier;
    }

  

    public JButton getjBtnSuivant() {
        return jBtnSuivant;
    }

  

    public JButton getjBtnSupprimer() {
        return jBtnSupprimer;
    }

  

    public JLabel getjLCodeArticle() {
        return jLCodeArticle;
    }

    public void setjLCodeArticle(JLabel jLCodeArticle) {
        this.jLCodeArticle = jLCodeArticle;
    }

    public JLabel getjLCodeCategorie() {
        return jLCodeCategorie;
    }

    public void setjLCodeCategorie(JLabel jLCodeCategorie) {
        this.jLCodeCategorie = jLCodeCategorie;
    }

    public JLabel getjLDesignation() {
        return jLDesignation;
    }

    public void setjLDesignation(JLabel jLDesignation) {
        this.jLDesignation = jLDesignation;
    }

    public JLabel getjLMessage() {
        return jLMessage;
    }

    public void setjLMessage(JLabel jLMessage) {
        this.jLMessage = jLMessage;
    }

    public JLabel getjLPrixUnit() {
        return jLPrixUnit;
    }

    public void setjLPrixUnit(JLabel jLPrixUnit) {
        this.jLPrixUnit = jLPrixUnit;
    }

    public JTextField getjTxtCodeArticle() {
        return jTxtCodeArticle;
    }

    public void setjTxtCodeArticle(JTextField jTxtCodeArticle) {
        this.jTxtCodeArticle = jTxtCodeArticle;
    }

    public JTextField getjTxtCodeCategorie() {
        return jTxtCodeCategorie;
    }

    public void setjTxtCodeCategorie(JTextField jTxtCodeCategorie) {
        this.jTxtCodeCategorie = jTxtCodeCategorie;
    }

    public JTextField getjTxtDesignation() {
        return jTxtDesignation;
    }

    public void setjTxtDesignation(JTextField jTxtDesignation) {
        this.jTxtDesignation = jTxtDesignation;
    }

    public JTextField getjTxtPrixUnit() {
        return jTxtPrixUnit;
    }

    public void setjTxtPrixUnit(JTextField jTxtPrixUnit) {
        this.jTxtPrixUnit = jTxtPrixUnit;
    }

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjout;
    private javax.swing.JButton jBtnAnnuler;
    private javax.swing.JButton jBtnDernier;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnNouveau;
    private javax.swing.JButton jBtnPrecedent;
    private javax.swing.JButton jBtnPremier;
    private javax.swing.JButton jBtnSuivant;
    private javax.swing.JButton jBtnSupprimer;
    private javax.swing.JLabel jLCodeArticle;
    private javax.swing.JLabel jLCodeCategorie;
    private javax.swing.JLabel jLDesignation;
    private javax.swing.JLabel jLMessage;
    private javax.swing.JLabel jLPrixUnit;
    private javax.swing.JPanel jPCentre;
    private javax.swing.JPanel jPMain;
    private javax.swing.JPanel jPNORD;
    private javax.swing.JPanel jPNord;
    private javax.swing.JPanel jPSUD;
    private javax.swing.JPanel jPSouth;
    private javax.swing.JTextField jTxtCodeArticle;
    private javax.swing.JTextField jTxtCodeCategorie;
    private javax.swing.JTextField jTxtDesignation;
    private javax.swing.JTextField jTxtPrixUnit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
