/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listofelement;

import javax.swing.DefaultListModel;

/**
 *
 * @author mk
 */
public class ddingElementToOurList extends javax.swing.JFrame {
    
    
    //On crée une liste qui nous permettra de rendre notre liste dynamique
    private DefaultListModel mCourriel = new DefaultListModel();
        
    
    /**
     * Creates new form JFListe
     */
    public ddingElementToOurList() {
        mCourriel.addElement("mail1@msn.com");
        mCourriel.addElement("mail2@msn.com");
        mCourriel.addElement("mail3@msn.com");
        mCourriel.addElement("mail4@msn.com");
        mCourriel.addElement("thismail@msn.com");
        initComponents();
        
        
        //Permet de connaitre le nombre d'élément dans la liste
        JNombreElement.setText("Nombre d'élément dans la liste: "+MaListe1.getModel().getSize());
        
        //Condition qui si la liste n'est pas vide
        if (MaListe1.getModel().getSize()>0) {
            MaListe1.setSelectedIndex(0);
            JLAffiche.setText("Vous avez selectionné "+MaListe1.getSelectedValue());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNordPanel = new javax.swing.JPanel();
        jInputAdress = new javax.swing.JTextField();
        JCenterPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MaListe1 = new javax.swing.JList<>();
        JEastPanel = new javax.swing.JPanel();
        Ajouter1 = new javax.swing.JButton();
        JSouthPanel = new javax.swing.JPanel();
        JLAffiche = new javax.swing.JLabel();
        JNombreElement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jInputAdress.setPreferredSize(new java.awt.Dimension(300, 35));
        JNordPanel.add(jInputAdress);

        getContentPane().add(JNordPanel, java.awt.BorderLayout.NORTH);

        JCenterPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        JCenterPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        MaListe1.setModel(mCourriel);
        MaListe1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MaListe1.setPreferredSize(new java.awt.Dimension(350, 200));
        MaListe1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MaListe1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(MaListe1);

        JCenterPanel1.add(jScrollPane2);

        getContentPane().add(JCenterPanel1, java.awt.BorderLayout.CENTER);

        JEastPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        JEastPanel.setPreferredSize(new java.awt.Dimension(120, 135));

        Ajouter1.setText("Ajouter");
        Ajouter1.setPreferredSize(new java.awt.Dimension(97, 45));
        Ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter1ActionPerformed(evt);
            }
        });
        JEastPanel.add(Ajouter1);

        getContentPane().add(JEastPanel, java.awt.BorderLayout.EAST);

        JSouthPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        JSouthPanel.setPreferredSize(new java.awt.Dimension(163, 135));
        JSouthPanel.setLayout(new java.awt.GridLayout(0, 1));

        JLAffiche.setText("Selectionnez un element");
        JSouthPanel.add(JLAffiche);
        JSouthPanel.add(JNombreElement);

        getContentPane().add(JSouthPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaListe1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MaListe1ValueChanged
        JLAffiche.setText("Vous avez selectioné: "+MaListe1.getSelectedValue());
    }//GEN-LAST:event_MaListe1ValueChanged

    private void Ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter1ActionPerformed
        mCourriel.addElement(jInputAdress.getText());        
        jInputAdress.setText("");
        //Nombre Element
        JNombreElement.setText("Nombre d'élément dans la liste: "+MaListe1.getModel().getSize());
    }//GEN-LAST:event_Ajouter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ddingElementToOurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ddingElementToOurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ddingElementToOurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ddingElementToOurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ddingElementToOurList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter1;
    private javax.swing.JPanel JCenterPanel1;
    private javax.swing.JPanel JEastPanel;
    private javax.swing.JLabel JLAffiche;
    private javax.swing.JLabel JNombreElement;
    private javax.swing.JPanel JNordPanel;
    private javax.swing.JPanel JSouthPanel;
    private javax.swing.JList<String> MaListe1;
    private javax.swing.JTextField jInputAdress;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
