/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package azcr3exercices;

/**
 *
 * @author mk
 */
public class Exercice1 extends javax.swing.JFrame {

    /**
     * Creates new form DExercices3JForm
     */
    public Exercice1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Centre = new javax.swing.JPanel();
        CentreNord = new javax.swing.JPanel();
        prenom = new javax.swing.JLabel();
        inputNom = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        inputPrenom = new javax.swing.JTextField();
        adresse = new javax.swing.JLabel();
        inpudAdress = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CentreSexe = new javax.swing.JPanel();
        Sexe = new javax.swing.JLabel();
        Homme = new javax.swing.JRadioButton();
        Femme = new javax.swing.JRadioButton();
        East = new javax.swing.JPanel();
        Tennis = new javax.swing.JCheckBox();
        Squash5 = new javax.swing.JCheckBox();
        Squash4 = new javax.swing.JCheckBox();
        Tennis2 = new javax.swing.JCheckBox();
        Squash3 = new javax.swing.JCheckBox();
        Squash2 = new javax.swing.JCheckBox();
        Tennis1 = new javax.swing.JCheckBox();
        Squash1 = new javax.swing.JCheckBox();
        Squash = new javax.swing.JCheckBox();
        Sud = new javax.swing.JPanel();
        OK = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercice3 JForm Design");
        setPreferredSize(new java.awt.Dimension(700, 400));

        Centre.setBackground(new java.awt.Color(255, 102, 102));
        Centre.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Centre.setToolTipText("");
        Centre.setLayout(new java.awt.BorderLayout());

        CentreNord.setBackground(new java.awt.Color(255, 102, 102));
        CentreNord.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        prenom.setText("Prenom");
        CentreNord.add(prenom);

        inputNom.setToolTipText("");
        inputNom.setEnabled(false);
        inputNom.setPreferredSize(new java.awt.Dimension(100, 22));
        inputNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomActionPerformed(evt);
            }
        });
        CentreNord.add(inputNom);

        nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nom.setText("Nom");
        CentreNord.add(nom);

        inputPrenom.setToolTipText("");
        inputPrenom.setPreferredSize(new java.awt.Dimension(100, 22));
        inputPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrenomActionPerformed(evt);
            }
        });
        CentreNord.add(inputPrenom);

        adresse.setText("Adresse");
        CentreNord.add(adresse);

        Centre.add(CentreNord, java.awt.BorderLayout.NORTH);

        inpudAdress.setBackground(new java.awt.Color(255, 102, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(450, 22));
        inpudAdress.setViewportView(jTextArea1);

        Centre.add(inpudAdress, java.awt.BorderLayout.CENTER);

        CentreSexe.setBackground(new java.awt.Color(255, 102, 102));
        CentreSexe.setAutoscrolls(true);

        Sexe.setText("Sexe:");
        CentreSexe.add(Sexe);

        Homme.setText("Homme");
        CentreSexe.add(Homme);

        Femme.setText("Femme");
        CentreSexe.add(Femme);

        Centre.add(CentreSexe, java.awt.BorderLayout.SOUTH);

        getContentPane().add(Centre, java.awt.BorderLayout.CENTER);

        East.setBackground(new java.awt.Color(0, 255, 51));
        East.setLayout(new java.awt.GridLayout(0, 1));

        Tennis.setText("Tennis");
        East.add(Tennis);

        Squash5.setText("Natation");
        East.add(Squash5);

        Squash4.setText("Squash");
        East.add(Squash4);

        Tennis2.setText("Tennis");
        East.add(Tennis2);

        Squash3.setText("Natation");
        East.add(Squash3);

        Squash2.setText("Squash");
        East.add(Squash2);

        Tennis1.setText("Tennis");
        East.add(Tennis1);

        Squash1.setText("Natation");
        East.add(Squash1);

        Squash.setText("Squash");
        East.add(Squash);

        getContentPane().add(East, java.awt.BorderLayout.EAST);

        Sud.setBackground(new java.awt.Color(255, 204, 51));

        OK.setText("OK");
        Sud.add(OK);

        Annuler.setText("Annuler");
        Sud.add(Annuler);

        getContentPane().add(Sud, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomActionPerformed

    private void inputPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPrenomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel Centre;
    private javax.swing.JPanel CentreNord;
    private javax.swing.JPanel CentreSexe;
    private javax.swing.JPanel East;
    private javax.swing.JRadioButton Femme;
    private javax.swing.JRadioButton Homme;
    private javax.swing.JButton OK;
    private javax.swing.JLabel Sexe;
    private javax.swing.JCheckBox Squash;
    private javax.swing.JCheckBox Squash1;
    private javax.swing.JCheckBox Squash2;
    private javax.swing.JCheckBox Squash3;
    private javax.swing.JCheckBox Squash4;
    private javax.swing.JCheckBox Squash5;
    private javax.swing.JPanel Sud;
    private javax.swing.JCheckBox Tennis;
    private javax.swing.JCheckBox Tennis1;
    private javax.swing.JCheckBox Tennis2;
    private javax.swing.JLabel adresse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane inpudAdress;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputPrenom;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    // End of variables declaration//GEN-END:variables
}
