/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meteoapplication;

/**
 *
 * @author mk
 */
public class JFMeteo extends javax.swing.JFrame {

    /**
     * Creates new form JFMeteo
     */
    public JFMeteo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupeTemp = new javax.swing.ButtonGroup();
        NordSection = new javax.swing.JPanel();
        Soleil = new javax.swing.JRadioButton();
        Nuage = new javax.swing.JRadioButton();
        Neige = new javax.swing.JRadioButton();
        CenterSection = new javax.swing.JPanel();
        JLmonResult = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        GroupeTemp.add(Soleil);
        Soleil.setText("Soleil");
        Soleil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoleilActionPerformed(evt);
            }
        });
        NordSection.add(Soleil);

        GroupeTemp.add(Nuage);
        Nuage.setText("Nuage");
        Nuage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuageActionPerformed(evt);
            }
        });
        NordSection.add(Nuage);

        GroupeTemp.add(Neige);
        Neige.setText("Neige");
        Neige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeigeActionPerformed(evt);
            }
        });
        NordSection.add(Neige);

        getContentPane().add(NordSection, java.awt.BorderLayout.NORTH);

        JLmonResult.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        JLmonResult.setText("MÉTEO");
        JLmonResult.setMaximumSize(new java.awt.Dimension(75, 22));
        CenterSection.add(JLmonResult);

        getContentPane().add(CenterSection, java.awt.BorderLayout.CENTER);

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuageActionPerformed
            JLmonResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meteoapplication/img/nuage.png")));
            JLmonResult.setText("");
        
    }//GEN-LAST:event_NuageActionPerformed

    private void SoleilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoleilActionPerformed
        JLmonResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meteoapplication/img/soleil.png")));
        JLmonResult.setText("");
    }//GEN-LAST:event_SoleilActionPerformed

    private void NeigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeigeActionPerformed
        JLmonResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meteoapplication/img/neige.png")));
        JLmonResult.setText("");
    }//GEN-LAST:event_NeigeActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        JLmonResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        JLmonResult.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        JLmonResult.setText("MÉTEO");
        JLmonResult.setMaximumSize(new java.awt.Dimension(75, 22));
        CenterSection.add(JLmonResult);
        
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMeteo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMeteo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterSection;
    private javax.swing.ButtonGroup GroupeTemp;
    private javax.swing.JLabel JLmonResult;
    private javax.swing.JRadioButton Neige;
    private javax.swing.JPanel NordSection;
    private javax.swing.JRadioButton Nuage;
    private javax.swing.JButton Reset;
    private javax.swing.JRadioButton Soleil;
    // End of variables declaration//GEN-END:variables
}
