/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az3cr5menuetdialogue;

/**
 *
 * @author Le Padre
 */
public class DJfmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public DJfmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPmnAnnuler = new javax.swing.JMenuItem();
        jPmnRemplacer = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnApplication = new javax.swing.JMenu();
        jMniQuitter = new javax.swing.JMenuItem();
        jMnEdition = new javax.swing.JMenu();
        jMniAjouter = new javax.swing.JMenuItem();
        jMniSupprimer = new javax.swing.JMenuItem();
        jMniEnleverSelection = new javax.swing.JMenuItem();

        jPmnAnnuler.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jPmnAnnuler.setMnemonic('A');
        jPmnAnnuler.setText("Annuler");
        jPmnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPmnAnnulerActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPmnAnnuler);

        jPmnRemplacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        jPmnRemplacer.setMnemonic('R');
        jPmnRemplacer.setText("Remplacer");
        jPmnRemplacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPmnRemplacerActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPmnRemplacer);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Menus");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Message ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jMnApplication.setMnemonic('A');
        jMnApplication.setText("Application");

        jMniQuitter.setText("Quitter");
        jMniQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniQuitterActionPerformed(evt);
            }
        });
        jMnApplication.add(jMniQuitter);

        jMenuBar1.add(jMnApplication);

        jMnEdition.setMnemonic('E');
        jMnEdition.setText("Edition");

        jMniAjouter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMniAjouter.setMnemonic('A');
        jMniAjouter.setText("Ajouter");
        jMniAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniAjouterActionPerformed(evt);
            }
        });
        jMnEdition.add(jMniAjouter);

        jMniSupprimer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMniSupprimer.setMnemonic('S');
        jMniSupprimer.setText("Supprimer");
        jMniSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniSupprimerActionPerformed(evt);
            }
        });
        jMnEdition.add(jMniSupprimer);

        jMniEnleverSelection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMniEnleverSelection.setMnemonic('e');
        jMniEnleverSelection.setText("Enlever Sélection");
        jMniEnleverSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniEnleverSelectionActionPerformed(evt);
            }
        });
        jMnEdition.add(jMniEnleverSelection);

        jMenuBar1.add(jMnEdition);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniAjouterActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Ajouter");
    }//GEN-LAST:event_jMniAjouterActionPerformed

    private void jMniSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniSupprimerActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Supprimer");
        
    }//GEN-LAST:event_jMniSupprimerActionPerformed

    private void jMniEnleverSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniEnleverSelectionActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Enlever Selection");
    }//GEN-LAST:event_jMniEnleverSelectionActionPerformed

    private void jMniQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniQuitterActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Quitter");
    }//GEN-LAST:event_jMniQuitterActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger())
        jPopupMenu1.show(jLabel1, evt.getX(), evt.getY());
        
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jPmnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPmnAnnulerActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Annuler");
    }//GEN-LAST:event_jPmnAnnulerActionPerformed

    private void jPmnRemplacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPmnRemplacerActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Remplacer");
    }//GEN-LAST:event_jPmnRemplacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DJfmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DJfmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DJfmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DJfmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DJfmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnApplication;
    private javax.swing.JMenu jMnEdition;
    private javax.swing.JMenuItem jMniAjouter;
    private javax.swing.JMenuItem jMniEnleverSelection;
    private javax.swing.JMenuItem jMniQuitter;
    private javax.swing.JMenuItem jMniSupprimer;
    private javax.swing.JMenuItem jPmnAnnuler;
    private javax.swing.JMenuItem jPmnRemplacer;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
